name: mobile
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.1.0
  animations: ^2.0.0
  camera_camera: ^2.0.1
  file_picker_cross: ^4.3.2
  flutter_map: ^0.12.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  image_picker: ^0.7.5
  latlong: ^0.6.1

  map_api:
    #    path: ../memorypath_map_api
    git:
      url: https://github.com/Memory-Path/memorypath_map_api.git
      ref: main
  memorypath_db_api:
    #    path: ../memorypath_database_api
    git:
      url: https://github.com/Memory-Path/memorypath_database_api.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  dartdoc: ^0.43.0

dependency_overrides:
  flutter_map: ^0.12.0
  quiver: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  logging: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
